spring:
  application:
    name: batch-rabbitmq

  rabbitmq:
    host: 192.168.0.101
    port: 5672
    username: admin
    password: admin
    template:
      default-receive-queue: my-queue
      

